workflows:
  build-web-and-deploy:
    name: Build Web & Deploy to Firebase
    max_build_duration: 20
    instance_type: mac_mini_m2

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    environment:
      flutter: stable
      groups:
        - firebase-deploy

    scripts:
      - name: Clean old builds
        script: flutter clean

      - name: Get dependencies
        script: flutter pub get

      - name: Build web release
        script: flutter build web --release

      - name: Ensure Firebase CLI
        script: |
          if ! command -v firebase &> /dev/null
          then
            echo "Installing Firebase CLI..."
            npm install -g firebase-tools
          else
            echo "Firebase CLI already exists"
          fi

      - name: Deploy to Firebase Hosting
        script: |
          firebase deploy --only hosting \
            --project we563-final-instagram-clone \
            --token $FIREBASE_TOKEN

    artifacts:
      - build/web
