name: we563_final_instagram_clone
description: "WE563 Final Project - Instagram Clone"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2 # Updated 2025-02-18
  device_preview: ^1.2.0 # Updated 2025-03-12
  flutter_secure_storage: ^9.2.4 # Updated 2025-01-10
  carousel_slider: ^4.2.1 # Updated 2025-04-05
  shimmer: ^3.0.0 # Updated 2023-05-20
  image_picker: ^1.0.7 # Updated 2025-04-15
  cupertino_icons: ^1.0.6 # Updated 2025-03-28

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Updated 2025-05-01

flutter:
  uses-material-design: true

  assets:
    - assets/images/
